import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css"

const jetBrains_Mono = JetBrains_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={jetBrains_Mono.className}>
      <body>
        <header>
          <Link href="./register">register</Link>
          <Link href="./login">login</Link>
          <a href="./calculator">calculator</a>
          <Link href="./">main</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
